// SPDX-License-Identifier: GPL-3.0-or-later
// Microcosm Android wrapper — a WebView shell around the built artifact.
// The sim runs as JS from file:///android_asset/index.html (generated by
// tools/build-app.js); this file adds nothing to the world and never will.
package org.microcosm.sandbox

import android.annotation.SuppressLint
import android.app.Activity
import android.graphics.Color
import android.os.Bundle
import android.view.WindowManager
import android.webkit.WebView
import android.webkit.WebViewClient

class MainActivity : Activity() {
    private lateinit var web: WebView

    @SuppressLint("SetJavaScriptEnabled")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // The world only advances while watched; keep the screen on so a
        // pocketed phone, not a screen timeout, is what pauses it.
        window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)

        web = WebView(this)
        web.setBackgroundColor(Color.parseColor("#05070C"))
        web.settings.javaScriptEnabled = true
        // Android multiplies WebView text by the system font-size setting;
        // the artifact is laid out in CSS px, so pin it to browser behavior.
        web.settings.textZoom = 100
        // Project rule: no localStorage — DOM storage stays at its default (off).
        web.settings.setSupportZoom(false)
        // Keep every navigation inside the wrapper; the artifact has no
        // external links today, and if one ever appears it must not silently
        // leave the app or reach the network.
        web.webViewClient = object : WebViewClient() {
            override fun shouldOverrideUrlLoading(view: WebView, url: String): Boolean =
                !url.startsWith("file:///android_asset/")
        }
        web.loadUrl("file:///android_asset/index.html")
        setContentView(web)
    }

    override fun onPause() { super.onPause(); web.onPause() }
    override fun onResume() { super.onResume(); web.onResume() }
    override fun onDestroy() { web.destroy(); super.onDestroy() }
}
