// 5.4 CORRIDOR CERTIFICATION: the locus may evolve freely inside [0,1] ONLY if both rails
// are proven safe. Runs the 8-seed ecology acceptance with every Drifta pinned at g=0
// (all faster-growing, no extra defense) and at g=1 (all tougher, slowest growth),
// mutation off so nothing moves. Criterion: the amended one -- the four core species
// persist to t=18,000 and the mineral audit stays flat; the apex is reported.
const path = require("path");
const CORE = path.join(__dirname, "..", "dist", "core.js");  // generated by tools/build.py
const C = require(CORE);
const { W, P } = C;
const TICKS = 18000;
P.mutation = false;
const auditM = () => { let t=0; for (let c=0;c<P.GRID*P.GRID;c++) t+=W.M[c]+W.dM[c];
  for (let i=0;i<W.n;i++) if (W.alive[i]) t+=W.mn[i]; for (let k=0;k<W.cN;k++) if (W.cAlive[k]) t+=W.cM[k]; return t; };
let anyFail = false;
for (const rail of [0, 1]){
  console.log(`\n=== rail g=${rail} (${rail ? "all tougher" : "all faster-growing"}), mutation off ===`);
  for (const seed of [11,22,33,44,55,66,77,88]){
    C.resetWorld(); C.initWorld(seed);
    for (let i=0;i<W.n;i++) if (W.alive[i] && W.sp[i]===1) W.g[i]=rail; // pin the founders; children inherit
    const M0 = auditM(); let ok=true, vLost=-1, vSeen=false, last=null;
    for (let t=0;t<=TICKS;t++){
      C.step();
      const p=[0,0,0,0,0,0,0]; for (let i=0;i<W.n;i++) if (W.alive[i]) p[W.sp[i]]++;
      last=p; if (p[6]>0) vSeen=true; else if (vSeen && vLost<0) vLost=t;
      if (p[0]===0||p[1]===0||p[3]===0||(t>950&&p[2]===0)){ console.log(`seed ${seed}: ECOSYSTEM COLLAPSE at t=${t} pops=${p}`); ok=false; anyFail=true; break; }
    }
    if (ok){
      let gm=0,n=0; for (let i=0;i<W.n;i++) if (W.alive[i]&&W.sp[i]===1){ gm+=W.g[i]; n++; }
      console.log(`seed ${seed}: OK apex ${!vSeen?"never":vLost<0?"held ("+last[6]+")":"lost t="+vLost} | S=${last[0]} D=${last[1]} C=${last[2]} B=${last[3]} | g pinned ${(gm/n).toFixed(2)} | audit ${(100*(auditM()-M0)/M0).toFixed(4)}%`);
    }
  }
}
console.log(anyFail ? "\nCORRIDOR: NOT CERTIFIED — a rail breaks the ecosystem" : "\nCORRIDOR CERTIFIED: both rails pass the ecosystem criterion on 8/8 seeds");
P.mutation = true;
process.exit(anyFail ? 1 : 0);
