// 5.4 CORRIDOR CERTIFICATION: a locus may evolve freely inside [0,1] ONLY if the rails are
// proven safe. Runs the 8-seed ecology acceptance at every CORNER of the corridor -- each
// species with a locus pinned at 0 or 1, all combinations -- mutation off so nothing moves.
// Criterion: the amended one -- the four core species persist to t=18,000 and the mineral
// audit stays flat; the apex is reported.
const path = require("path");
const CORE = path.join(__dirname, "..", "dist", "core.js");  // generated by tools/build.py
const C = require(CORE);
const { W, P, TRAITS } = C;
const LOCI = []; for (let sp=0;sp<7;sp++) if (TRAITS[sp].locus) LOCI.push(sp);
const corners = []; for (let m=0; m < (1<<LOCI.length); m++) corners.push(LOCI.map((sp,k) => [sp, (m>>k)&1]));
const TICKS = 18000;
P.mutation = false;
const auditM = () => { let t=0; for (let c=0;c<P.GRID*P.GRID;c++) t+=W.M[c]+W.dM[c];
  for (let i=0;i<W.n;i++) if (W.alive[i]) t+=W.mn[i]; for (let k=0;k<W.cN;k++) if (W.cAlive[k]) t+=W.cM[k]; return t; };
let anyFail = false;
for (const corner of corners){
  const label = corner.map(([sp,r]) => TRAITS[sp].name+" "+(r ? TRAITS[sp].locus.hiWord : TRAITS[sp].locus.loWord)).join(" + ");
  console.log(`\n=== corner: ${label}, mutation off ===`);
  for (const seed of [11,22,33,44,55,66,77,88]){
    C.resetWorld(); C.initWorld(seed);
    for (const [sp,r] of corner) for (let i=0;i<W.n;i++) if (W.alive[i] && W.sp[i]===sp) W.g[i]=r; // pin the founders; children inherit
    const M0 = auditM(); let ok=true, vLost=-1, vSeen=false, last=null;
    for (let t=0;t<=TICKS;t++){
      C.step();
      const p=[0,0,0,0,0,0,0]; for (let i=0;i<W.n;i++) if (W.alive[i]) p[W.sp[i]]++;
      last=p; if (p[6]>0) vSeen=true; else if (vSeen && vLost<0) vLost=t;
      if (p[0]===0||p[1]===0||p[3]===0||(t>950&&p[2]===0)){ console.log(`seed ${seed}: ECOSYSTEM COLLAPSE at t=${t} pops=${p}`); ok=false; anyFail=true; break; }
    }
    if (ok){
      console.log(`seed ${seed}: OK apex ${!vSeen?"never":vLost<0?"held ("+last[6]+")":"lost t="+vLost} | S=${last[0]} D=${last[1]} C=${last[2]} B=${last[3]} | audit ${(100*(auditM()-M0)/M0).toFixed(4)}%`);
    }
  }
}
console.log(anyFail ? "\nCORRIDOR: NOT CERTIFIED — a corner breaks the ecosystem" : `\nCORRIDOR CERTIFIED: all ${corners.length} corners pass the ecosystem criterion on 8/8 seeds`);
P.mutation = true;
process.exit(anyFail ? 1 : 0);
