// 5.5 PHASE GATE: the Observatory must narrate the evolution unprompted.
//
// Eight seeds, the shipped (evolving) world against the reference (silent) control:
//   1. sweep narrated   -- a "sweep" event fires within 18,000 ticks on >= 6/8 evolving seeds
//   2. grounded         -- at the tick it fires, the locus-mean channel is >= g0 + 0.10 and
//                          the population majority sits on that side (the event is read off the
//                          instrument, not off the sim)
//   3. variance visible -- the locus-sd channel at t=18,000 exceeds its value at t=2,000 on
//                          every evolving seed (the fuel gauge moves)
//   4. control silent   -- the reference world emits zero heredity events and its sd channel
//                          reads exactly 0 on 8/8 seeds
//   5. cycle change reproduced -- the 5.2 measurement on seed 22 (period, phase, end-of-run
//                          mean g) matches the recorded harness/yoshida.js result on this build
const path = require("path");
const CORE = path.join(__dirname, "..", "dist", "core.js");  // generated by tools/build.js
const C = require(CORE);
const { W, P, REC, TRAITS } = C;
const SEEDS = [11,22,33,44,55,66,77,88], TICKS = 18000;
const L = TRAITS[1].locus;
const chan = (back, ch) => W.rec[((W.recHead-back+REC.N)%REC.N)*REC.CH + ch];

function run(seed, mutation){
  P.mutation = mutation; C.resetWorld(); C.initWorld(seed);
  let sd2k = -1, sweepMeanAtFire = null, sweepShareAtFire = null, sweepTick = -1;
  for (let t=1;t<=TICKS;t++){
    C.step();
    if (t === 2000) sd2k = chan(1, 49+1);
    if (sweepTick < 0){
      const ev = W.sysEvents.find(e => e.type === "sweep" && e.sp === 1);
      if (ev){ sweepTick = ev.tick; sweepMeanAtFire = chan(1, 42+1);
        let hi=0,n=0; for (let i=0;i<W.n;i++) if (W.alive[i]&&W.sp[i]===1){ n++; if (W.g[i]>L.g0+0.05) hi++; }
        sweepShareAtFire = hi/Math.max(1,n); }
    }
  }
  const hered = W.sysEvents.filter(e => e.type==="sweep" || e.type==="uniform");
  return { sweepTick, sweepMeanAtFire, sweepShareAtFire, sd2k, sd18k: chan(1, 49+1), mean18k: chan(1, 42+1), hered };
}

console.log("=== evolving world (P.mutation=true) ===");
const ev = {}, ref = {};
for (const s of SEEDS){ ev[s] = run(s, true);
  const r = ev[s];
  console.log(`seed ${s}: sweep ${r.sweepTick>0 ? "t="+r.sweepTick+" (mean "+r.sweepMeanAtFire.toFixed(2)+", "+Math.round(100*r.sweepShareAtFire)+"% tougher)" : "none"} | sd 2k ${r.sd2k.toFixed(3)} -> 18k ${r.sd18k.toFixed(3)} | mean 18k ${r.mean18k.toFixed(2)} | events: ${r.hered.map(e=>e.type+"@"+e.tick).join(" ")||"-"}`); }
console.log("\n=== reference world (P.mutation=false) ===");
for (const s of SEEDS){ ref[s] = run(s, false);
  const r = ref[s];
  console.log(`seed ${s}: heredity events ${r.hered.length} | sd 18k ${r.sd18k} | mean 18k ${r.mean18k.toFixed(2)}`); }

const c1n = SEEDS.filter(s => ev[s].sweepTick > 0).length, c1 = c1n >= 6;
const c2 = SEEDS.every(s => ev[s].sweepTick < 0 || (ev[s].sweepMeanAtFire >= L.g0 + 0.10 && ev[s].sweepShareAtFire >= 0.6));
const c3 = SEEDS.every(s => ev[s].sd18k > ev[s].sd2k);
const c4 = SEEDS.every(s => ref[s].hered.length === 0 && ref[s].sd18k === 0);

// 5. reproduce the 5.2 measurement on seed 22 with this build (numbers recorded from harness/yoshida.js)
const RECORDED = { seed: 22, pOff: 6420, pOn: 1600, phOff: 0.04, phOn: 0.00, gEnd: 0.77 }; // 5.6 coevolving world
const STRIDE = 20, SKIP = 150;
function series(seed, mutation){ P.mutation = mutation; C.resetWorld(); C.initWorld(seed);
  const D=[], G=[]; let gEnd=0;
  for (let t=1;t<=30000;t++){ C.step(); if (t%STRIDE) continue; let d=0,c=0,gm=0;
    for (let i=0;i<W.n;i++){ if(!W.alive[i]) continue; if(W.sp[i]===1){ d++; gm+=W.g[i]; } else if(W.sp[i]===2) c++; }
    D.push(d); G.push(c); gEnd = d?gm/d:0; }
  return { D:D.slice(SKIP), G:G.slice(SKIP), gEnd }; }
const demean = xs => { const m=xs.reduce((a,b)=>a+b,0)/xs.length; return xs.map(v=>v-m); };
function xcorr(a,b,lag){ let s=0,n=0,sa=0,sb=0; for(let i=0;i<a.length;i++){ const j=i+lag; if(j<0||j>=b.length) continue; s+=a[i]*b[j]; sa+=a[i]*a[i]; sb+=b[j]*b[j]; n++; } return n>10 ? s/Math.sqrt((sa||1)*(sb||1)) : 0; }
function period(x){ let crossed=false,best=-1,bestV=-1; for(let Lg=1;Lg<x.length/2;Lg++){ const v=xcorr(x,x,Lg); if(!crossed){ if(v<0) crossed=true; continue; } if(v>bestV){bestV=v;best=Lg;} else if(best>0&&Lg>best+5&&v<bestV-0.05) break; } return best>0?best:NaN; }
function phaseLag(a,b,per){ let best=0,bestV=-2; const Lg=Math.round(per); for(let k=-Lg;k<=Lg;k++){ const v=xcorr(a,b,k); if(v>bestV){bestV=v;best=k;} } let f=best/per; while(f>0.5)f-=1; while(f<=-0.5)f+=1; return f; }
const off = series(22,false), on = series(22,true);
const Do=demean(off.D), Go=demean(off.G), Dn=demean(on.D), Gn=demean(on.G);
const pOff=period(Do)*STRIDE, pOn=period(Dn)*STRIDE, phOff=phaseLag(Do,Go,pOff/STRIDE), phOn=phaseLag(Dn,Gn,pOn/STRIDE);
const got = { pOff, pOn, phOff:+phOff.toFixed(2), phOn:+phOn.toFixed(2), gEnd:+on.gEnd.toFixed(2) };
const c5 = got.pOff===RECORDED.pOff && got.pOn===RECORDED.pOn && got.phOff===RECORDED.phOff && got.phOn===RECORDED.phOn && got.gEnd===RECORDED.gEnd;

console.log("\n=== gate criteria ===");
console.log(`1. sweep narrated on >= 6/8 evolving seeds: ${c1?"PASS":"FAIL"} (${c1n}/8)`);
console.log(`2. every sweep grounded in the instrument (mean >= g0+0.10, majority >= 60%): ${c2?"PASS":"FAIL"}`);
console.log(`3. variance channel rises 2k -> 18k on 8/8: ${c3?"PASS":"FAIL"}`);
console.log(`4. control silent (0 heredity events, sd channel exactly 0) on 8/8: ${c4?"PASS":"FAIL"}`);
console.log(`5. 5.2 measurement reproduced on this build (seed 22): ${c5?"PASS":"FAIL"} got ${JSON.stringify(got)} recorded ${JSON.stringify(RECORDED)}`);
const passed = c1&&c2&&c3&&c4&&c5;
console.log(`\nGATE: ${passed ? "ALL CRITERIA PASS — the Observatory narrates the evolution unprompted" : "NOT PASSED — see failures above"}`);
P.mutation = true;
process.exit(passed ? 0 : 1);
