// Shared harness primitives. Every acceptance and experiment script builds on these so a
// measurement means the same thing everywhere. Pure functions over the exported core.
const path = require("path");
const CORE = process.env.MC_CORE || path.join(__dirname, "..", "dist", "core.js");  // generated by tools/build.py; MC_CORE overrides (historical builds, ports)
const C = require(CORE);
const { W, P, TRAITS, REC } = C;

const { SPECIES } = C;
const SEEDS = [11,22,33,44,55,66,77,88];
const HORIZON = 18000;                       // the acceptance horizon (ticks)
const LOCI = SPECIES.LOCI;

function pops(){ const p=[0,0,0,0,0,0,0]; for (let i=0;i<W.n;i++) if (W.alive[i]) p[W.sp[i]]++; return p; }
function auditM(){ let t=0; for (let c=0;c<P.GRID*P.GRID;c++) t+=W.M[c]+W.dM[c];
  for (let i=0;i<W.n;i++) if (W.alive[i]) t+=W.mn[i]; for (let k=0;k<W.cN;k++) if (W.cAlive[k]) t+=W.cM[k]; return t; }
function locusStats(sp, plane){ // mean, sd and rail shares of one locus (default: the display locus) among the living of one species
  const off = (plane||0)*C.MAXN;
  let n=0,m=0,m2=0,lo=0,hi=0; for (let i=0;i<W.n;i++){ if (!W.alive[i]||W.sp[i]!==sp) continue; const g=W.g[off+i]; n++; m+=g; m2+=g*g; if (g<0.02) lo++; if (g>0.98) hi++; }
  const mean = n? m/n : 0; return { n, mean, sd: n? Math.sqrt(Math.max(0, m2/n-mean*mean)) : 0, railLo: n? lo/n : 0, railHi: n? hi/n : 0 }; }
const fmtG = s => s.mean.toFixed(2)+"±"+s.sd.toFixed(2);
function start(seed, mutation){ P.mutation = mutation; C.resetWorld(); C.initWorld(seed); }
function pin(corner){ // entries [sp, g] pin the display locus; [sp, g, plane] pins that plane
  for (const [sp,g,plane] of corner){ const off = (plane||0)*C.MAXN;
    for (let i=0;i<W.n;i++) if (W.alive[i] && W.sp[i]===sp) W.g[off+i]=g; } }
// the amended ecosystem criterion: the four core species persist; the apex is reported, not required
function coreCollapsed(p, t){ // a core species gone; the grazer only counts after its founding transient
  return SPECIES.CORE.some(sp => p[sp]===0 && (sp !== SPECIES.GRAZER || t > 950)); }

// Cycle analysis (5.2). Series are demeaned samples; lags in samples.
const demean = xs => { const m = xs.reduce((a,b)=>a+b,0)/xs.length; return xs.map(v=>v-m); };
// linear detrend: founding and secular trends push the ACF negative for good and hide the cycle
function detrend(xs){ const n=xs.length; let sx=0,sy=0,sxy=0,sxx=0;
  for (let i=0;i<n;i++){ sx+=i; sy+=xs[i]; sxy+=i*xs[i]; sxx+=i*i; }
  const b=(n*sxy-sx*sy)/((n*sxx-sx*sx)||1), a=(sy-b*sx)/n; return xs.map((v,i)=>v-(a+b*i)); }
function xcorr(a, b, lag){ let s=0,n=0,sa=0,sb=0;
  for (let i=0;i<a.length;i++){ const j=i+lag; if (j<0||j>=b.length) continue; s+=a[i]*b[j]; sa+=a[i]*a[i]; sb+=b[j]*b[j]; n++; }
  return n>10 ? s/Math.sqrt((sa||1)*(sb||1)) : 0; }
function period(x){ // lag of the first ACF peak AFTER the ACF has gone negative and come back up
  // (the earlier version stopped inside the descending trough and returned ~a quarter period;
  //  harness/selftest.js guards this now)
  let phase = 0, best=-1, bestV=-Infinity;   // 0: before first negative, 1: in the trough, 2: rising/peak search
  for (let L=1; L<x.length/2; L++){ const v = xcorr(x,x,L);
    if (phase === 0){ if (v < 0) phase = 1; continue; }
    if (phase === 1){ if (v > 0) phase = 2; else continue; }
    if (v > bestV){ bestV = v; best = L; } else if (best > 0 && L > best + 3 && v < bestV - 0.05) break; }
  return best>0 ? best : NaN; }
function phaseLag(a, b, per){ // lag of peak cross-correlation as a fraction of the period, in (-0.5, 0.5]
  let best=0, bestV=-2; const L=Math.round(per);
  for (let k=-L;k<=L;k++){ const v=xcorr(a,b,k); if (v>bestV){ bestV=v; best=k; } }
  let f=best/per; while (f>0.5) f-=1; while (f<=-0.5) f+=1; return { frac:f, r:bestV }; }
const cv = x => { const m=x.reduce((a,b)=>a+b,0)/x.length; const v=x.reduce((a,b)=>a+(b-m)*(b-m),0)/x.length; return Math.sqrt(v)/(m||1); };
// population + locus-mean series for the cycle experiments
function series(seed, mutation, ticks=30000, stride=20, skipTicks=3000){
  start(seed, mutation); const D=[], G=[]; let gEnd=0;
  for (let t=1;t<=ticks;t++){ C.step(); if (t%stride) continue; let d=0,c=0,gm=0;
    for (let i=0;i<W.n;i++){ if(!W.alive[i]) continue; if(W.sp[i]===SPECIES.PREY){ d++; gm+=W.g[i]; } else if(W.sp[i]===SPECIES.GRAZER) c++; }
    D.push(d); G.push(c); gEnd = d? gm/d : 0; }
  const skip = skipTicks/stride; return { D:D.slice(skip), G:G.slice(skip), gEnd }; }
function cycleMetrics(seed){ // the 5.2 measurement for one seed, mutation off vs on
  const off = series(seed,false), on = series(seed,true);
  const Do=detrend(off.D), Go=detrend(off.G), Dn=detrend(on.D), Gn=detrend(on.G);
  const pOff=period(Do), pOn=period(Dn);
  return { seed, pOff:pOff*20, pOn:pOn*20, phOff:+phaseLag(Do,Go,pOff).frac.toFixed(2), phOn:+phaseLag(Dn,Gn,pOn).frac.toFixed(2),
    cvOff:+cv(off.D).toFixed(2), cvOn:+cv(on.D).toFixed(2), gEnd:+on.gEnd.toFixed(2) }; }

// Movement analysis (MV.0). Tracks are position samples of ONE organism; unwrap removes the torus
// so displacements accumulate, msd is time-origin-averaged, and msdAlpha is the log-log slope of
// MSD(tau) over a lag window: ~1 diffusive, ~2 ballistic, ->0 confined. harness/selftest.js guards
// all three on synthetic tracks (the period estimator's lesson applied in advance).
function unwrapTrack(xs){ const out=[xs[0]]; for (let i=1;i<xs.length;i++) out.push(out[i-1]+C.wd(xs[i]-xs[i-1])); return out; }
function msd(xs, ys, maxLag){ // xs/ys already unwrapped
  const Lmax = Math.min(maxLag, Math.floor(xs.length/2)), out=[];
  for (let lag=1;lag<=Lmax;lag++){ let s=0,n=0;
    for (let i=0;i+lag<xs.length;i++){ const dx=xs[i+lag]-xs[i], dy=ys[i+lag]-ys[i]; s+=dx*dx+dy*dy; n++; }
    out.push(n ? s/n : 0); }
  return out; }
function msdAlpha(m, from, to){ // least-squares slope of log MSD vs log tau over lags [from, to] (1-based; defaults: all)
  const lo = Math.max(1, from||1), hi = Math.min(m.length, to||m.length);
  let sx=0,sy=0,sxy=0,sxx=0,n=0;
  for (let lag=lo;lag<=hi;lag++){ const v=m[lag-1]; if (v<=0) continue;
    const lx=Math.log(lag), ly=Math.log(v); sx+=lx; sy+=ly; sxy+=lx*ly; sxx+=lx*lx; n++; }
  return n>=3 ? (n*sxy-sx*sy)/((n*sxx-sx*sx)||1) : NaN; }

module.exports = { C, W, P, TRAITS, REC, SPECIES, SEEDS, HORIZON, LOCI, pops, auditM, locusStats, fmtG, start, pin, coreCollapsed,
  demean, detrend, xcorr, period, phaseLag, cv, series, cycleMetrics, unwrapTrack, msd, msdAlpha };
