// 5.2 THE YOSHIDA EXPERIMENT: does heritable prey defense transform the predator-prey cycle?
//
// Same seeds, mutation on vs off -- a controlled evolution experiment the real chemostats
// needed heroic effort to run, free here by determinism. Literature prediction (Yoshida et al.
// 2003, 2007): with evolvable prey the cycle period LENGTHENS and the grazer-prey phase shifts
// from the classic quarter-period lag toward antiphase; in the cryptic regime total prey stays
// flat while genotypes churn beneath. Reported honestly whatever it shows.
//
// Method: Drifta (ch 1) and Cilio (ch 2) counts every 20 ticks over 30,000 ticks, first 3,000
// discarded (founding transient), mean removed. Period = lag of the first autocorrelation peak.
// Phase = lag of the peak cross-correlation, in fractions of a period (positive: Cilio follows
// Drifta; 0.25 = quarter lag, 0.5 = antiphase). Cryptic check: coefficient of variation of the
// Drifta series -- evolution flattening totals while g moves is the signature.
const path = require("path");
const CORE = path.join(__dirname, "..", "dist", "core.js");  // generated by tools/build.py
const C = require(CORE);
const { W, P } = C;
const TICKS = 30000, STRIDE = 20, SKIP = 3000/STRIDE;

function series(seed, mutation){
  P.mutation = mutation; C.resetWorld(); C.initWorld(seed);
  const D=[], G=[], g=[];
  for (let t=1;t<=TICKS;t++){
    C.step();
    if (t % STRIDE) continue;
    let d=0,c=0,gm=0;
    for (let i=0;i<W.n;i++){ if(!W.alive[i]) continue; if(W.sp[i]===1){ d++; gm+=W.g[i]; } else if(W.sp[i]===2) c++; }
    D.push(d); G.push(c); g.push(d?gm/d:0);
  }
  return { D:D.slice(SKIP), G:G.slice(SKIP), gEnd:g[g.length-1] };
}
const demean = xs => { const m = xs.reduce((a,b)=>a+b,0)/xs.length; return xs.map(v=>v-m); };
function xcorr(a, b, lag){ // normalized cross-correlation at lag (b shifted later by lag)
  let s=0, n=0, sa=0, sb=0;
  for (let i=0;i<a.length;i++){ const j=i+lag; if(j<0||j>=b.length) continue; s+=a[i]*b[j]; sa+=a[i]*a[i]; sb+=b[j]*b[j]; n++; }
  return n>10 ? s/Math.sqrt((sa||1)*(sb||1)) : 0;
}
function period(x){ // first local maximum of the ACF beyond the first zero crossing
  let crossed=false, best=-1, bestV=-1;
  for (let L=1; L<x.length/2; L++){
    const v = xcorr(x,x,L);
    if (!crossed){ if (v<0) crossed=true; continue; }
    if (v>bestV){ bestV=v; best=L; }
    else if (best>0 && L>best+5 && v<bestV-0.05) break;
  }
  return best>0 ? best : NaN;
}
function phaseLag(a, b, per){
  let best=0, bestV=-2;
  const L = Math.round(per);
  for (let k=-L; k<=L; k++){ const v = xcorr(a,b,k); if (v>bestV){ bestV=v; best=k; } }
  let f = best/per; while (f>0.5) f-=1; while (f<=-0.5) f+=1;
  return { frac:f, r:bestV };
}
const cv = x => { const m=x.reduce((a,b)=>a+b,0)/x.length; const v=x.reduce((a,b)=>a+(b-m)*(b-m),0)/x.length; return Math.sqrt(v)/(m||1); };

console.log("seed  | period off  on   | phase off   on    | Drifta CV off  on   | g end");
const rows = [];
for (const seed of [11,22,33,44,55,66,77,88]){
  const off = series(seed,false), on = series(seed,true);
  const Do=demean(off.D), Go=demean(off.G), Dn=demean(on.D), Gn=demean(on.G);
  const pOff=period(Do), pOn=period(Dn);
  const phOff=phaseLag(Do,Go,pOff), phOn=phaseLag(Dn,Gn,pOn);
  const r = { seed, pOff:pOff*STRIDE, pOn:pOn*STRIDE, phOff:phOff.frac, phOn:phOn.frac, cvOff:cv(off.D), cvOn:cv(on.D), gEnd:on.gEnd };
  rows.push(r);
  console.log(`${String(seed).padEnd(5)} | ${String(r.pOff).padStart(6)} ${String(r.pOn).padStart(6)} | ${r.phOff.toFixed(2).padStart(6)} ${r.phOn.toFixed(2).padStart(6)} | ${r.cvOff.toFixed(2).padStart(9)} ${r.cvOn.toFixed(2).padStart(5)} | ${r.gEnd.toFixed(2)}`);
}
const mean = k => rows.reduce((a,r)=>a+r[k],0)/rows.length;
const sd = k => { const m=mean(k); return Math.sqrt(rows.reduce((a,r)=>a+(r[k]-m)**2,0)/rows.length); };
console.log("\n=== ensemble (mean +- sd over 8 seeds) ===");
console.log(`period   off ${mean("pOff").toFixed(0)} +- ${sd("pOff").toFixed(0)} ticks   on ${mean("pOn").toFixed(0)} +- ${sd("pOn").toFixed(0)} ticks   (literature: lengthens)`);
console.log(`phase    off ${mean("phOff").toFixed(2)} +- ${sd("phOff").toFixed(2)}         on ${mean("phOn").toFixed(2)} +- ${sd("phOn").toFixed(2)}         (0.25 quarter lag -> 0.5 antiphase)`);
console.log(`Drifta CV off ${mean("cvOff").toFixed(2)} +- ${sd("cvOff").toFixed(2)}        on ${mean("cvOn").toFixed(2)} +- ${sd("cvOn").toFixed(2)}        (cryptic regime: on << off)`);
const longer = rows.filter(r=>r.pOn>r.pOff).length, toward = rows.filter(r=>Math.abs(r.phOn)>Math.abs(r.phOff)).length;
console.log(`\nperiod longer on ${longer}/8 seeds; phase farther from zero on ${toward}/8 seeds`);
P.mutation = true;
